package dependencies

object BuildDependenciesVersions {
    const val KOTLIN = "1.3.72"
    const val ANDROIDX_APPCOMPAT = "1.1.0"
    const val ANDROIDX_CORE_KTX_V = "1.2.0"
    const val ANDROIDX_LEGACY_V = "1.0.0"
    const val ANDROID_FRAGMENT_KTX_V = "1.2.4"
    const val ANDROIDX_CONSTRAINT_LAYOUT_V = "2.0.0-beta5"
    const val LIFECYCLE_VIEWMODEL_KTX_V = "2.2.0"
    const val VIEW_MODEL_SAVED_STATE_V = "2.2.0"
    const val RETROFIT = "2.6.4"
    const val DAGGER = "2.23.2"
    const val DAGGER_ASSISTED_INJECTION_V = "0.3.3"
    const val GLIDE = "4.10.0"
    const val GLIDE_TRANSFORMATION = "3.3.0"
    const val GLIDE_OKHTTP_INTEGRATION = "4.10.0"
    const val ROOM_V = "2.2.5"
    const val ROOM_COMPILER_V = "2.2.2"
    const val MATERIAL_DESIGN_V = "1.2.0-alpha06"
    const val DESIGN_SUPPORT_LIB ="1.0.0"
    const val GSON_V = "2.6.4"
    const val DATA_BINDING_COMPILER_V = "3.5.0"
    const val NAVIGATION_V = "2.2.2"
    const val KOTLIN_COROUTINES_V = "1.2.0-alpha"
    const val GOOGLE_PLAY_SERVICE_AUTH = "17.0.0"
    const val EVENT_BUS_V = "3.1.1"
    const val CIRCULAR_IMAGE_V = "3.1.0"
    const val MULTI_DEX_V = "2.0.1"
    const val COROUTINE_SCOPE = "2.2.0"
    const val FB_STETHO = "1.5.1"
    const val TIMBER_V = "4.7.1"
    const val LOTTIE_V = "3.3.1"
    const val RX_JAVA_V = "2.2.6"
    const val RX_ANDROID_V = "2.1.1"
    const val FLOWABLE_TEXTVIEW_V = "2.0.5"
    const val THREE_TEN_APP_V = "1.0.5"
    const val PAGINATION = "2.1.2"

    object Test {
        const val JUNIT = "4.13"
        const val ANDROID_JUNIT = "1.1.1"
        const val ANDROID_RUNNER = "1.2.0"
        const val ANDROIDX_ESPRESSO = "3.2.0"
        const val ROBOLECTRIC = "4.3"
        const val ROBOLECTRIC_MULTIDEX = "4.0.1"
        const val MOCKITO = "2.11.0"
        const val ARCH_TEST = "2.1.0"
    }
}